version: '3.8'
services: 
    main:
        build: 
            context: .
            dockerfile: Dockerfile
        command: 'php artisan serve --host=0.0.0.0:8000'
        volumes:
            - .:/app
        ports:
            - 8000:8000
        depends_on: 
            - db
        networks:
        - app-network

    queue:
        build: 
            context: .
            dockerfile: Dockerfile
        command: 'php artisan queue:work'
        depends_on: 
            - db
        networks:
        - app-network        

    db:
        platform: linux/x86_64
        image: mysql:8.0
        environment: 
            MYSQL_DATABASE: cards_schema
            MYSQL_ROOT_PASSWORD: root
            MYSQL_TCP_PORT: 3307
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 3307:3307
        expose:
            - "3307"    
        networks:
        - app-network
#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
